# Site settings
title: "Rezza Fadillah - Resume"
description: "Rezza Fadillah - Resume."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar: "true"
resume_name: "Rezza Fadillah"
resume_title: "Technical Lead"

# used for the contact button in _layouts/resume.html
resume_contact_email: "rez.fadillah@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone: "+6281313069822"
resume_contact_address: Jakarta, Indonesia"

resume_header_contact_info: Jakarta, Indonesia • +6281313069822 • rez.fadillah@gmail.com"
display_header_contact_info: false"

resume_header_intro: "<p>Innovative and results-driven software developer with a strong background in building and maintaining high-performance applications, including flash sales systems and microservices architectures. Adept at leading and collaborating within cross-functional teams to deliver complex projects on time. Currently seeking opportunities to leverage my expertise in software development and leadership to drive impactful technological solutions and advance my career in a dynamic environment</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work: "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience: true
resume_section_education: true
resume_section_projects: true
resume_section_skills: true
# resume_section_recognition: true
# resume_section_links: true
# resume_section_associations: true
# resume_section_interests: true
resume_section_languages: true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  # resume_github_url: "https://github.com/jglovier/resume-template"
  # resume_twitter_url: "http://twitter.com/jglovier"
  # resume_dribbble_url: "https://dribbble.com/jag"
  # resume_facebook_url: "insert Facebook URL here"
  resume_linkedin_url: "https://www.linkedin.com/in/rezza-fadillah"
  # resume_instagram_url: "insert your Instagram URL here"
  # resume_website_url: "http://joelglovier.com"
  # resume_medium_url: "https://medium.com/@jglovier"
resume_print_social_links: true

# Design settings
resume_theme: default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
